## Need sudo to add ppas
sudo: required

language: cpp
compiler: gcc
branches:
  only:
    - unstable

before_install:
  ## For gcc 4.8
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  ## For OpenCV
  - sudo add-apt-repository ppa:yjwong/opencv2 -y
  ## For latest Boost
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  ## Use Miniconda for Python.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export MINICONDA_BIN=/home/travis/miniconda/bin
  - export PYTHONPATH=/home/travis/miniconda/lib/python2.7/site-packages
  - sudo rm /usr/lib/libpython2.7.so
  - sudo ln -s /home/travis/miniconda/lib/libpython2.7.so.1.0 /usr/lib/libpython2.7.so
  - sudo rm /usr/lib/libpython2.7.so.1.0
  - sudo ln -s /home/travis/miniconda/lib/libpython2.7.so.1.0 /usr/lib/libpython2.7.so.1.0
  - export PATH=$MINICONDA_BIN:$PATH

install:
  ## GLOG
  - wget https://github.com/google/glog/archive/v0.3.4.zip
  - unzip v0.3.4.zip
  - cd glog-0.3.4
  - ./configure && sudo make && sudo make install
  - cd ..
  ## PROTOBUF
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.zip
  - unzip protobuf-2.6.1.zip  
  - cd protobuf-2.6.1
  - sudo ./configure && sudo make && sudo make install
  - cd ..
  ## HDF5
  - wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.14.tar.gz
  - gunzip < hdf5-1.8.14.tar.gz | tar xf -
  - cd hdf5-1.8.14
  - ./configure --prefix=/usr/local/hdf5 && make && sudo make install
  - export HDF5_ROOT=/usr/local/hdf5
  - cd ..
  - protoc --version
  - valgrind --version
  ## apt-get dependencies
  - sudo apt-get install -qq m4 libboost1.55-all-dev libeigen3-dev libopencv-dev libopenblas-dev valgrind
  ## conda dependencies
  - conda update --yes conda
  - travis_retry conda install --yes pip scipy scikit-image scikit-learn jinja2 matplotlib pillow scons numpy
  ## Python
  - sudo $MINICONDA_BIN/pip install networkx
  - sudo $MINICONDA_BIN/pip install cppheaderparser
  - sudo $MINICONDA_BIN/pip install ply
  ## Dataset
  - wget jamie.shotton.org/work/data/WeizmannMultiScale.zip
  - unzip WeizmannMultiScale.zip -d WeizmannHorseDataset

before_script:
  - git submodule update --init --recursive
  - export EIGEN_ROOT=/usr/include/eigen3

script:
  - $MINICONDA_BIN/scons --generate-interfaces
  - $MINICONDA_BIN/scons --with-serialization --with-tests --with-examples --with-python --with-caffe --cpu-only --caffe-model-dir=/home/travis/caffe-models
  - cd fertilized_tests
  - valgrind --leak-check=full --show-reachable=yes --suppressions=./fertilized_tests.supp ./fertilized_tests --run_test=Correctness*/*
  - cd ../Presentation
  - $MINICONDA_BIN/python run_examples_as_tests.py /home/travis/WeizmannHorseDataset

after_success: true

after_failure:
  - cat config.log

after_script: true

