sudo: required

language: cpp
compiler: gcc
branches:
  only:
    - unstable

notifications:
  email:
    on_success: changed
    on_failure: changed

before_install:
  ## Use Miniconda for Python.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export MINICONDA_BIN=/home/travis/miniconda/bin
  - export PYTHONPATH=/home/travis/miniconda/lib/python2.7/site-packages
  - sudo rm /usr/lib/libpython2.7.so
  - sudo ln -s /home/travis/miniconda/lib/libpython2.7.so.1.0 /usr/lib/libpython2.7.so
  - sudo rm /usr/lib/libpython2.7.so.1.0
  - sudo ln -s /home/travis/miniconda/lib/libpython2.7.so.1.0 /usr/lib/libpython2.7.so.1.0
  - sudo /home/travis/miniconda/bin/conda update --yes conda
  - sudo /home/travis/miniconda/bin/conda install --yes pip
  - export PATH=$MINICONDA_BIN:$PATH

install:
  - sudo ./setup_environment.sh --quiet --ub12 --pyenabled --nomat --nocaffe /home/travis/caffe-models --cpu-only --suppress-caffe-model-download /home/travis/miniconda/bin
  ## valgrind
  - sudo apt-get install -qq libc6-dbg > allout.txt 2>&1
  - wget http://valgrind.org/downloads/valgrind-3.10.1.tar.bz2 > allout.txt 2>&1
  - tar -xvf valgrind-3.10.1.tar.bz2 > allout.txt 2>&1
  - cd valgrind-3.10.1
  - ./configure > allout.txt 2>&1 && make > allout.txt 2>&1 && sudo make install > allout.txt 2>&1
  - cd ..

before_script:
  - export OMP_NUM_THREADS=2

script:
  - source setup_paths.sh
  - scons --with-tests --with-examples
  - cd fertilized_tests
  - valgrind --leak-check=full --show-reachable=yes --suppressions=./fertilized_tests.supp ./fertilized_tests --run_test=Correctness*/*
  - cd ..

after_failure:
  - cat config.log

