sudo: required

language: cpp
compiler: gcc
python: 2.7
branches:
  only:
    - unstable

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
  - sudo apt-get install -qq m4 doxygen libboost-all-dev libeigen3-dev \
      python-ply python-scipy libopencv-dev
  - sudo pip install networkx
  - sudo pip install jinja2 cppheaderparser pillow \
      scikit-image matplotlib scikit-learn numpy

before_script:
  - git submodule update --init --recursive
  - export EIGEN_ROOT=/usr/local/include/eigen3

script:
  - scons --generate-interfaces
  - scons --with-serialization --with-tests --with-examples --with-python

after_success: true

after_failure: true

after_script: true

