sudo: required

language: cpp
compiler: gcc
branches:
  only:
    - dev_cmake

env:
    - BUILD_WITH_SERIALIZATION_WO_PYTHON=true
      PYTHON_VERSION="none"
    - BUILD_WITH_SERIALIZATION_WO_PYTHON=false
      PYTHON_VERSION="2"
    - BUILD_WITH_SERIALIZATION_WO_PYTHON=false
      PYTHON_VERSION="3"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - mkdir build
  - cd build

install:
  ## C++ libraries and compiler.
  - sudo apt-get -y install libboost-thread1.55-dev \
                            libboost-system1.55-dev \
                            libboost-test1.55-dev \
                            libboost-filesystem1.55-dev \
                            libboost-date-time1.55-dev \
                            libboost-serialization1.55-dev \
                            libboost-python1.55-dev
  - sudo apt-get -y install build-essential g++-4.8
  ## Eigen3.
  - wget http://bitbucket.org/eigen/eigen/get/3.2.5.tar.gz
  - tar -xzvf 3.2.5.tar.gz
  ## Python (must be setup after boost was installed).
  - source build_support/travis/setup_python.sh
  ## CMake.
  - export CMAKE_C_COMPILER=gcc-4.8
  - export CMAKE_CXX_COMPILER=g++-4.8
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh
  - chmod a+x cmake-3.2.3-Linux-x86_64.sh
  - sudo ./cmake-3.2.3-Linux-x86_64.sh --skip-license --prefix=/usr/local
  - export PATH=/usr/local/bin:$PATH
  - cmake --version

before_script:
  - export OMP_NUM_THREADS=2
  - export CC=/usr/bin/gcc-4.8
  - export CXX=/usr/bin/g++-4.8
  - export CTEST_OUTPUT_ON_FAILURE=1
  - export CTEST_PARALLEL_LEVEL=1

script:
  - source ../build_support/travis/cmake_call.sh
  - cmake --build . -- -j2
  - cmake --build . --target test

after_failure:
  - cat CMakeFiles/CMakeOutput.log
