## Need sudo to add ppas
sudo: required

language: cpp
compiler: gcc
branches:
  only:
    - unstable

before_install:
  ## For gcc 4.8
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  ## For OpenCV
  - sudo add-apt-repository ppa:yjwong/opencv2 -y
  ## For latest Boost
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  ## Use Miniconda for Python.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export MINICONDA_BIN=/home/travis/miniconda/bin
  - export PYTHONPATH=/home/travis/miniconda/lib/python2.7/site-packages
  - export PATH=$MINICONDA_BIN:$PATH

install:
  - sudo apt-get install -qq m4 libboost1.55-all-dev libeigen3-dev libopencv-dev python-numpy
  - conda update --yes conda
  - travis_retry conda install --yes pip scipy scikit-image scikit-learn jinja2 matplotlib pillow scons numpy
  - sudo $MINICONDA_BIN/pip install networkx
  - sudo $MINICONDA_BIN/pip install cppheaderparser
  - sudo $MINICONDA_BIN/pip install ply

before_script:
  - git submodule update --init --recursive
  - export EIGEN_ROOT=/usr/include/eigen3

script:
  - $MINICONDA_BIN/scons --generate-interfaces
  - $MINICONDA_BIN/scons --with-serialization --with-tests --with-examples --with-python

after_success: true

after_failure:
  - cat config.log
  - which python
  - python -c "import numpy"
  - python -c "import numpy.linalg"
  - cat .sconf_temp/conftest_10.out
  - cat .sconf_temp/conftest_11.out
  - ./.sconf_temp/conftest_11

after_script: true

