sudo: required

language: cpp
compiler: gcc
branches:
  only:
    - dev_cmake

notifications:
  email:
    on_success: changed
    on_failure: changed

before_install:
  ## Use Miniconda for Python.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export MINICONDA_BIN=/home/travis/miniconda/bin
  - export PYTHONPATH=/home/travis/miniconda/lib/python2.7/site-packages
  - sudo rm /usr/lib/libpython2.7.so
  - sudo ln -s /home/travis/miniconda/lib/libpython2.7.so.1.0 /usr/lib/libpython2.7.so
  - sudo rm /usr/lib/libpython2.7.so.1.0
  - sudo ln -s /home/travis/miniconda/lib/libpython2.7.so.1.0 /usr/lib/libpython2.7.so.1.0
  - sudo /home/travis/miniconda/bin/conda update --yes --quiet conda
  - sudo /home/travis/miniconda/bin/conda install --yes --quiet pip
  - export PATH=$MINICONDA_BIN:$PATH
  ## Setup the build environment.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq

install:
  - sudo /home/travis/miniconda/bin/conda install --yes --quiet networkx ply numpy scipy pillow scikit-image matplotlib scikit-learn
  - sudo apt-get -y install libboost-thread1.55-dev libboost-system1.55-dev libboost-test1.55-dev libboost-filesystem1.55-dev libboost-date-time1.55-dev libboost-serialization1.55-dev libboost-python1.55-dev
  - sudo apt-get -y install build-essential g++-4.8
  - sudo ldconfig
  ## CMake
  - export CMAKE_C_COMPILER=g++-4.8
  - export CMAKE_CXX_COMPILER=g++-4.8
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh
  - chmod a+x cmake-3.2.3-Linux-x86_64.sh
  - sudo ./cmake-3.2.3-Linux-x86_64.sh --skip-license --prefix=/usr/local
  - export PATH=/usr/local/bin:$PATH
  - cmake --version

before_script:
  - export OMP_NUM_THREADS=2
  - export CXX=/usr/bin/g++-4.8
  - export CC=/usr/bin/g++4.8
  - mkdir build
  - cd build

script:
  - cmake ..
  - cmake --build .
  - cmake --build . --target=test
