branches:
  only:
    - unstable

environment:
  EIGEN_ROOT: C:\test
  ANACONDA_ROOT: C:\Anaconda
  ANACONDA_BIN: C:\Anaconda\bin

install:
  - set EIGEN_ROOT=C:\Test
  - set ANACONDA_ROOT=C:\Anaconda
  - set ANACONDA_BIN=%ANACONDA_ROOT%\bin
  - echo $(ANACONDA_BIN)
  - echo %ANACONDA_BIN%
  - dir
  ## miniconda
  - appveyor DownloadFile http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe
  - Miniconda-latest-Windows-x86_64.exe /S /D=%ANACONDA_ROOT%
  - $ANACONDA_BIN\conda update --yes conda
  - $ANACONDA_BIN\conda install --yes pip scipy scikit-image scikit-learn jinja2 matplotlib pillow scons numpy
  ## Python
  - $ANACONDA_BIN\pip install networkx
  - $ANACONDA_BIN\pip install cppheaderparser
  - $ANACONDA_BIN\pip install ply
  - nuget install protobuf -OutputDirectory deps -ExcludeVersion
  - nuget install boost -OutputDirectory deps -ExcludeVersion
  - nuget install OpenCV -OutputDirectory deps -ExcludeVersion
  - nuget install Eigen -OutputDirectory deps -ExcludeVersion
  - nuget install hdf5-v120 -OutputDirectory deps -ExcludeVersion
  - nuget install OpenBLAS -OutputDirectory deps -ExcludeVersion
  ## Dataset
  ## - wget jamie.shotton.org/work/data/WeizmannMultiScale.zip
  ## - unzip WeizmannMultiScale.zip -d WeizmannHorseDataset
  - dir
  - cd deps
  - dir
  - cd ..

before_build:
  - git submodule update --init --recursive

build_script:
  - $ANACONDA_BIN\scons --generate-interfaces
  - $ANACONDA_BIN\scons --with-serialization --with-tests --with-examples --with-python --with-caffe --cpu-only --caffe-model-dir=/home/travis/caffe-models
  - cd fertilized_tests
  - fertilized_tests --run_test=Correctness*/*
  - cd ..
  - cd Presentation
  - $ANACONDA_BIN\python run_examples_as_tests.py /home/travis/WeizmannHorseDataset

on_failure:
  - type config.log

test_script: echo Tests

