branches:
  only:
    - unstable

install:
  - set EIGEN_ROOT=C:\Test
  - set ANACONDA_ROOT=C:\Anaconda
  - set ANACONDA_BIN=%ANACONDA_ROOT%\bin
  - dir
  ## miniconda
  - appveyor DownloadFile http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe
  - Miniconda-latest-Windows-x86_64.exe /S /D=C:\Anaconda
  - cd C:\Anaconda
  - dir
  - cd Tools\Scripts
  - dir
  - cd ..\..\Scripts
  - dir
  - cd C:\projects\fertilized-forests
  - C:\Anaconda\Scripts\conda update --yes conda
  - C:\Anaconda\Scripts\conda install --yes pip scipy scikit-image scikit-learn jinja2 matplotlib pillow scons numpy
  ## Python
  - C:\Anaconda\Scripts\pip install networkx
  - C:\Anaconda\Scripts\pip install cppheaderparser
  - C:\Anaconda\Scripts\pip install ply
  - mkdir deps
  - mkdir deps\include
  - mkdir deps\lib
  - nuget install protobuf -OutputDirectory deps -ExcludeVersion
  - nuget install boost -OutputDirectory deps -ExcludeVersion
  - nuget install OpenCV -OutputDirectory deps -ExcludeVersion
  - nuget install Eigen -OutputDirectory deps -ExcludeVersion
  - nuget install hdf5-v120 -OutputDirectory deps -ExcludeVersion
  - nuget install OpenBLAS -OutputDirectory deps -ExcludeVersion
  ## Dataset
  ## - wget jamie.shotton.org/work/data/WeizmannMultiScale.zip
  ## - unzip WeizmannMultiScale.zip -d WeizmannHorseDataset
  - dir
  - cd deps
  - dir
  - cd ..

before_build:
  - git submodule update --init --recursive

build_script:
  - C:\Anaconda\Scripts\scons --generate-interfaces
  - C:\Anaconda\Scripts\scons --with-serialization --with-tests --with-examples --with-python --with-caffe --cpu-only --caffe-model-dir=/home/travis/caffe-models
  - cd fertilized_tests
  - fertilized_tests --run_test=Correctness*/*
  - cd ..
  - cd Presentation
  - C:\Anaconda\python run_examples_as_tests.py /home/travis/WeizmannHorseDataset

on_failure:
  - type config.log

test_script: echo Tests

