branches:
  only:
    - unstable

install:
  - set EIGEN_ROOT=C:\projects\fertilized-forests\deps\Eigen
  - set BOOST_ROOT=C:\projects\fertilized-forests\deps\boost
  - set HDF5_ROOT=C:\projects\fertilized-forests\deps\hdf5-v120
  - set OPENBLAS_ROOT=C:\projects\fertilized-forests\deps\OpenBLAS
  - set OPENCV_ROOT=C:\projects\fertilized-forests\deps\OpenCV
  - set OPENCV_VERSION=2410
  - set OPENCV_LIB_DIR=C:\projects\fertilized-forests\deps\OpenCV\x64\vc12\lib
  - set PROTOBUF_ROOT=C:\projects\fertilized-forests\deps\protobuf
  - set PROTOC=C:\projects\fertilized-forests\deps\protobuf\vsprojects\x64\Release\protoc.exe
  - set ANACONDA_ROOT=C:\Anaconda
  - set ANACONDA_BIN=%ANACONDA_ROOT%\bin
  - set 
  - dir
  ## miniconda
  - appveyor DownloadFile http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe
  - Miniconda-latest-Windows-x86_64.exe /S /D=C:\Anaconda
  - cd C:\projects\fertilized-forests
  - C:\Anaconda\Scripts\conda update --yes conda
  - C:\Anaconda\Scripts\conda install --yes pip scipy scikit-image scikit-learn jinja2 matplotlib pillow scons numpy
  ## Python
  - C:\Anaconda\Scripts\pip install networkx
  - C:\Anaconda\Scripts\pip install cppheaderparser
  - C:\Anaconda\Scripts\pip install ply
  - C:\Anaconda\Scripts\pip install pypiwin32 --allow-external pywin32 --allow-unverified pywin32
  - mkdir deps
  - nuget install protobuf -OutputDirectory deps -ExcludeVersion
  - cd deps\protobuf
  - dir
  - cd ..\..
  - nuget install boost -OutputDirectory deps -ExcludeVersion
  - cd deps\boost
  - dir
  - cd ..\..
  - nuget install OpenCV -OutputDirectory deps -ExcludeVersion
  - cd deps\OpenCV
  - dir
  - cd ..\..
  - nuget install Eigen -OutputDirectory deps -ExcludeVersion
  - cd deps\Eigen
  - dir
  - cd ..\..
  - nuget install hdf5-v120 -OutputDirectory deps -ExcludeVersion
  - cd deps\hdf5-v120
  - dir
  - cd ..\..
  - nuget install OpenBLAS -OutputDirectory deps -ExcludeVersion
  - cd deps\OpenBLAS
  - dir
  - cd ..\..
  ## Dataset
  ## - wget jamie.shotton.org/work/data/WeizmannMultiScale.zip
  ## - unzip WeizmannMultiScale.zip -d WeizmannHorseDataset

before_build:
  - git submodule update --init --recursive

build_script:
  - C:\Anaconda\Scripts\scons --generate-interfaces
  - C:\Anaconda\Scripts\scons --with-serialization --with-tests --with-examples --with-python --with-caffe --cpu-only --caffe-model-dir=/home/travis/caffe-models
  - cd fertilized_tests
  - fertilized_tests --run_test=Correctness*/*
  - cd ..
  - cd Presentation
  - C:\Anaconda\python run_examples_as_tests.py /home/travis/WeizmannHorseDataset

on_failure:
  - type config.log

test_script: echo Tests

