branches:
  only:
    - unstable

install:
  - set ANACONDA_ROOT=C:\Anaconda
  - set ANACONDA_BIN=%ANACONDA_ROOT%\bin
  ## miniconda
  - appveyor DownloadFile http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe
  - Miniconda-latest-Windows-x86_64.exe /S /D=C:\Anaconda
  - cd C:\projects\fertilized-forests
  - C:\Anaconda\Scripts\conda update --yes --quiet conda
  - C:\Anaconda\Scripts\conda install --yes --quiet pip
  - cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC"
  - vcvarsall.bat amd64
  - cd C:\projects\fertilized-forests

build_script:
  - setup_environment.bat --quiet C:\Anaconda --nopy --nomat --nocaffe --nopath --cpu-only --suppress-caffe-model-download
  - setup_paths.bat
  - C:\Anaconda\Scripts\scons --with-tests

on_failure:
  - type config.log

test_script:
  - cd fertilized_tests
  - fertilized_tests --run_test=Correctness*/*
  - cd ..

