branches:
  only:
    - unstable

environment:
  EIGEN_ROOT: C:\test
  

install:
  - dir
  ## miniconda
  - appveyor DownloadFile http://repo.continuum.io/miniconda/Miniconda-latest-Windows-x86_64.exe
  - Miniconda-latest-Windows-x86_64.exe /S /D=C:\Anaconda
  - conda update --yes conda
  - conda install --yes pip scipy scikit-image scikit-learn jinja2 matplotlib pillow scons numpy
  ## Python
  - pip install networkx
  - pip install cppheaderparser
  - pip install ply
  - nuget install protobuf -OutputDirectory deps -ExcludeVersion
  - nuget install boost -OutputDirectory deps -ExcludeVersion
  - nuget install OpenCV -OutputDirectory deps -ExcludeVersion
  - nuget install Eigen -OutputDirectory deps -ExcludeVersion
  - nuget install hdf5-v120 -OutputDirectory deps -ExcludeVersion
  - nuget install OpenBLAS -OutputDirectory deps -ExcludeVersion
  ## Dataset
  ## - wget jamie.shotton.org/work/data/WeizmannMultiScale.zip
  ## - unzip WeizmannMultiScale.zip -d WeizmannHorseDataset
  - dir
  - cd deps
  - dir
  - cd ..

before_build:
  - git submodule update --init --recursive

build_script:
  - scons --generate-interfaces
  - scons --with-serialization --with-tests --with-examples --with-python --with-caffe --cpu-only --caffe-model-dir=/home/travis/caffe-models
  - cd fertilized_tests
  - fertilized_tests --run_test=Correctness*/*
  - cd ..
  - cd Presentation
  - $MINICONDA_BIN/python run_examples_as_tests.py /home/travis/WeizmannHorseDataset

on_failure:
  - type config.log

test_script: echo Tests

